### ISSUE TITLE
Project setup is a bit outdated and could be improved to be even more useful

### ISSUE THREAD

**Issue by mateuszkwiecinski** [gradle/gradle-issue-reproducer#3]
I tried today to leverage this reproducer template and I can share some feedback:
1. It uses old Gradle version by default https://github.com/gradle/gradle-issue-reproducer/blob/e9a71a12db2b5756863c0d25dc336731c9131a37/gradle/wrapper/gradle-wrapper.properties#L3. I'm fairly sure such a repro would be immediately suspicious and I'd be asked to use at lest latest stable (or idealy: latest RC)
3. The `.gitignore` could automatically exclude more of config files for the most common IDEs (like IntelliJ and VSCode)
so when committing, I don't have to worry about such files
<img width="310" alt="image" src="https://user-images.githubusercontent.com/36954793/216784794-aba9ea33-6fea-45f2-8a56-d54aea9312c0.png">
4. There is no `.editorconfig` which would help in avoiding unnecessary diffs like these:
<img width="1314" alt="image" src="https://user-images.githubusercontent.com/36954793/216784877-3fa7a82d-5cf9-4f1d-af1e-726a3b5b2f05.png">
or missing newline characters:
<img width="134" alt="image" src="https://user-images.githubusercontent.com/36954793/216784905-2ed73884-7519-4ae2-b6ef-13a1a2f587f8.png">
5. the pipeline uses old versions of actions (setup-java, actions/checkout), which forces me to research how they worked a year ago to properly configure the repro. It is usually easier to bump them on my own, but still, it defeats the purpose of using a template.  

In overall, it felt like I still have to configure the project from the beginning, with additional overhead of being surprised by more _old_ things, that don't work in a way I expect them to, which in the end discourages people (just me?) from using it.

Since this reproducer is [still recommended](https://github.com/gradle/gradle/issues/23700#issuecomment-1415532446) to use when reporting issues, I'd suggest you to well... maintain it. Given how simple the project is, it would be enough if you setup tool like https://github.com/renovatebot/renovate that would keep your actions/dependencies/default Gradle version up-to-date.

**Comment by ljacomet** [comment]
Suggested changes have been implemented through #5 and #6
