### ISSUE TITLE
Provide build/settings.gradle.kts instead of Groovy

### ISSUE THREAD

**Issue by cloudshiftchris** [gradle/gradle-issue-reproducer#4]

**Comment by mateuszkwiecinski** [comment]
I think this is already available. You can switch the branch to https://github.com/gradle/gradle-issue-reproducer/tree/kotlin-dsl

**Comment by cloudshiftchris** [comment]
Ah, yes, I see.  Would be good to document that option, and perhaps not default to either (appears to default to Groovy).

**Comment by ljacomet** [comment]
Kotlin is now the default to align with Gradle strategy and both READMEs indicate that there is a template with the other DSL available.
