### ISSUE TITLE
Gradle template

### ISSUE THREAD

**Issue by Danjhop4** [gradle/gradle-issue-reproducer#8]
@Danjhop4 Hello. I believe you are referencing 
* https://github.com/gradle/gradle/issues/26191

You are wrong about  "they won’t except anything but this". We do accept any type of reproducer if it properly represents the issue. The problem with the issue was you not giving us enough information about the problem.

_Originally posted by @ov7a in https://github.com/gradle/gradle-issue-reproducer/issues/7#issuecomment-1719064003_
What does count then?
The template is what they pointed me to despite my saying it was made by gradle it self as I needed a baseline but did not know how to set up buildscripts from scratch and the template misses that

**Comment by Danjhop4** [comment]
So I can’t use that template plus I would have to mod it to work with my setup

**Comment by big-guy** [comment]
I'm closing and locking this issue.

I made a longer post over on the [original issue](https://github.com/gradle/gradle/issues/26191#issuecomment-1720057426).
